### ISSUE TITLE
waos

### ISSUE THREAD

**Issue by iFrzdy** [vowxky/DeathMessagePlus#1]
épico bro, estaría bueno poner un comando o un .json o .txt tipo config para configurar el color/formato del texto, para los q no saben de código, pero buen mod papu 👍 💯

**Comment by vowxky** [comment]
De hecho esa idea ya la estaba pensando , de aqui un rato y deja veo que actualizo el mod para poder hacer eso :))

**Comment by vowxky** [comment]
Listo , agregado un config el cual permite poner colores y ponerlo en el display de action bar o en el chat

**Comment by iFrzdy** [comment]
nanana este tipo esta a otro nivel
